variable "vpc_cidr" {}
variable "vpc_name" {}
variable "igw_name" {}
variable "route_cidr" {}
variable "route_name" {}
variable "sub_cidr" {}
variable "sub_name" {}
variable "sg_name" {}
variable "instance_count" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_pair_name" {}
variable "env" {}
